# Generated by Django 6.0.3 on 2026-04-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('rider', 'Rider'), ('sender', 'Sender')], max_length=50),
        ),
    ]
