# Generated by Django 6.0.3 on 2026-04-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address_text',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255),
        ),
    ]
