# Generated by Django 6.0.3 on 2026-04-26 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxapi', '0003_alter_customerprofile_default_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycode',
            old_name='code_a',
            new_name='customer_code',
        ),
        migrations.RenameField(
            model_name='deliverycode',
            old_name='code_b',
            new_name='rider_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fluxapi.company'),
        ),
    ]
